# Generated by Django 3.2.9 on 2021-12-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('origin_diary', models.TextField()),
                ('japanese_translation', models.TextField()),
                ('own_english_text', models.TextField()),
                ('english_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('is_completed', models.CharField(default='unchecked', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaries', models.PositiveIntegerField(default=0)),
                ('completed_diaries', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='user_date_unique'),
        ),
    ]
