# Generated by Django 3.2.9 on 2021-12-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
