# Generated by Django 3.2.9 on 2021-12-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
